---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by luo20.
--- DateTime: 2025/9/4 11:25
---
-- 点赞key
local blogLiked = KEYS[1]
-- 点赞数量key（新增）
local blogLikeCount = KEYS[2]
-- 用户id
local userId = ARGV[1]
-- 博客id
local blogId = ARGV[2]
-- 时间戳
local timestamp = ARGV[3]

-- 返回值结果 -1 取消点赞，1 点赞
local result

-- 判断当前用户是否已经点赞 应该用 false 来判断是否存在
if (redis.call('ZSCORE', blogLiked, userId) ~= false) then
    -- 如果已点赞，取消点赞
    redis.call('zrem', blogLiked, userId)
    redis.call('HINCRBY', blogLikeCount, blogId, -1)  -- 计数器减1
    result = -1  -- 取消点赞
else
    -- 如果未点赞，可以点赞
    redis.call('zadd', blogLiked, timestamp ,userId)
    redis.call('HINCRBY', blogLikeCount, blogId, 1)   -- 计数器加1
    result = 1  -- 成功点赞
end

return result