---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by luo20.
--- DateTime: 2025/8/26 21:44
---

--1.参数列表
--1.1优惠券id
local voucherId = ARGV[1]
--1.2用户id
local userId = ARGV[2]
--1.3订单id
local orderId = ARGV[3]
--1.4 当前时间
local now = ARGV[4]
--2.数据key
--2.1 库存key
local seckillKey = 'hm-DianPing:seckill:type:' ..voucherId
--2.2 订单key
local orderKey = 'hm-DianPing:seckill:order:' ..voucherId

--3.脚本业务
--3.0 判断秒杀时间是否开始 HGET stockKey beginTime
local beginTime = redis.call('HGET',seckillKey,'beginTime')
-- beginTime ~= false  ~=意思是!= 检查nil的,nil意思是键不存在
if(beginTime ~= false and beginTime > now) then
--    秒杀时间尚未开始
    return -1
end
--3.0.1 判断秒杀时间是否结束 HGET stockKey endTime
local endTime = redis.call('HGET',seckillKey,'endTime')
if(endTime ~= false and endTime < now) then
--    秒杀时间已结束
    return -2
end
--3.1判断库存账是否充足 HGET stockKey stock
if (tonumber(redis.call('hget', seckillKey,'stock')) <= 0) then
--    3.2库存不足 返回1
    return 1
end
--3.2 判断用户是否下单 SISMEMBER orderKey userId
if (redis.call('sismember',orderKey,userId) == 1) then
--    3.3存在，说明是重复下单，返回2
    return 2
end
--3.4库存充足，下单成功，库存-1 incrby stockKey -1
redis.call('hincrby', seckillKey, 'stock', -1)
--3.3下单(保存用户) SADD orderKey userId
redis.call('sadd', orderKey, userId)
--3.4发送到消息队列中 XADD stream.orders * k1 v1 k2 v2
redis.call('xadd', 'stream.orders', '*', 'userId', userId, 'voucherId', voucherId, 'id', orderId)
return 0

